#!/bin/bash
#!sum n numers

echo "enter the number of variables to add"
read n
echo "enter the numbers"
for ((i=1; i<=n; i++))
do
read num
        if  [[ $num =~ [0-9] ]]; then
                somma=$((somma + num))
        fi
done
echo $somma > risultato
cat risultato
