#!/bin/bash
#!sum 5 numbers

echo "enter five numbers"
for ((i=1; i<=5; i++))
do
read num
        if  [[ $num =~ [0-9] ]]; then
                somma=$((somma + num))
        fi
done
echo $somma > risultato
cat risultato
